repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        types: [file, python]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
    -   id: nbqa-black
    -   id: nbqa-pyupgrade
        args: [--py39-plus]
    -   id: nbqa-isort
    -   id: nbqa-flake8
