name: bart-experiments
channels:
  - conda-forge
dependencies:
  - blas
  - jax
  - jupyter
  - scikit-learn
  - pip
  - pre-commit
  - python=3.9
  - pip:
    - "git+https://github.com/pymc-devs/pymc.git@main"
    - "git+https://github.com/arviz-devs/arviz.git@main"
