name: bart-experiments
channels:
  - conda-forge
dependencies:
  - aeppl=0.0.28
  - aesara=2.6.2
  - arviz=0.12.0
  - blas
  - flake8
  - jax
  - jupyter
  - matplotlib=3.4
  - numpy=1.20
  - pandas=1.2
  - pip
  - pre-commit
  - python=3.9
  - pip:
    - black[jupyter]
    - "git+https://github.com/pymc-devs/pymc.git@main"
