name: bart-line-profiler
channels:
  - conda-forge
dependencies:
  - blas
  - jupyter
  - scikit-learn
  - pip
  - pre-commit
  - python=3.12
  - pymc==5.13.1
  - arviz==0.18.0
  - pip:
    - argparse==1.4.0
    - matplotlib==3.8.4
    - memray==1.12.0
    # This branch contains the line_profiler decorator on specific PGBART functions
    - git+https://github.com/GStechschulte/pymc-bart.git@line-profiler
    - snakeviz==2.2.0
    - line_profiler==4.1.2
